# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-05 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='candidate')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('content_max_20_words', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='employe')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('content_max_20_words', models.TextField()),
                ('job_type', models.CharField(choices=[('PART TIME', 'Part Time'), ('FULL TIME', 'Full Time'), ('URGENT', 'Urgent')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='We_work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company')),
            ],
        ),
    ]
